### PR TITLE
:bug: Fix image options type #116

### PR DESCRIPTION
**Pull request by ShaunaTheDead86**
[Issue #116](https://github.com/etro-js/etro/issues/116)

> In [line 4](https://github.com/clabe45/vidar/blob/master/src/layer/image.ts#L4) of image.ts, the type ImageOptions is set to be the same as VisualOptions, when it really should be the same as VisualSourceOptions. VisualSourceOptions includes necessary fields for visual layers with an HTML element as its source. We just need to use this type instead of VisualOptions.

### CODE REVIEW

**Comment by clabe45** [comment]
Hello, and thank you for contributing! It think your commit changes a bunch of line endings. Could you please run the following command if you are using Windows:
```bash
git config --global core.autocrlf true
```
and this otherwise:
```bash
git config --global core.autocrlf input
```

And then you'll need to renormalize the line endings before committing again (it's fine to make multiple commits, I can squash them into one when I merge the PR):
```bash
git add --renormalize .
```

**Comment by ShaunaTheDead86** [comment]
Thanks! I fixed the line endings. I was wondering why all those files had been changed when I hadn't touched them. I thought maybe the process of running "npm run build" had modified them. 

This is my first contribution so I wasn't entirely sure what I was doing! I appreciate the help :)

**Comment by clabe45** [comment]
No worries at all! It looks great now, except for one last thing. Can you please make a commit that undoes the changes to package-lock.json? They're probably okay, but they might break something down the road.

By the way, that test that failed was broken before your PR, so besides package-lock.json everything looks fine!

**Comment by clabe45** [comment]
Looks great! Thanks again :D

Merging

**Comment by clabe45** [comment]
By the way, what version of npm are you using? Perhaps I should make a new issue for updating the dependencies in package-lock?

**Comment by ShaunaTheDead86** [comment]
Great! :)

And I'm using version 8.11.0 of npm

**Pull request merged**
