### PR TITLE
Replace discord link with badge on README.md

### LINKED ISSUE #223: Replace discord link with badge

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
fix #223

Hi [clabe45](https://github.com/clabe45),
this is my PR for the issue, please check it out

### CODE REVIEW

**Review by clabe45 — CHANGES_REQUESTED** [review]
Hey, just got back from a trip. Can you please move the badge up to the top of the page with the other badges?

**Comment by clabe45** [comment]
Can you move the discord badge with the badges up above line 5?

**Comment by viktoriussuwandi** [comment]
sure no problem @clabe45, already move the discord next to other badges on top

**Review by clabe45 — APPROVED** [review]
Looks great, thanks!!

**Pull request merged**
